select*from [Table] where color = 'blue'
select*from [Table] where mark = 'apple'
select*from [Table] where [customer name]='ali'
select*from[Table] where [price back cover]='700'
DELETE FROM [Table] where [color ]='yellow'
DELETE FROM [Table] where [mark ]='nokia'
DELETE FROM [Table] where [mark ]='nothing phone'
DELETE FROM [Table] where [mark ]='samsung'
update [Table] set [color ]='pink' where [color ]='black'
update [Table] set [mark ] ='13pro' where [mark ] ='15pro'
update [Table] set [mark ] ='nokia' where [mark ] ='apple'
update [Table] set [mark ] ='apple' where [mark ] ='samsung'
